apiVersion: apps/v1
kind: Deployment
metadata:
  name: archgen-dev-architecture-service
  labels:
    app: architecture-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architecture-service
  template:
    metadata:
      labels:
        app: architecture-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: archgen-dev-architecture-service-sa
      containers:
        - name: architecture-service
          image: "acrarchgendev.azurecr.io/architecture-service:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "archgen-dev-architecture-keyvault-provider"
