apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: archgen-dev-project-service-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "00000000-0000-0000-0000-000000000000"
    keyvaultName: "kv-archgen-dev"
    objects: |
      array:
        - |
          objectName: cosmos-connection-string
          objectType: secret
          objectAlias: COSMOS_CONNECTION_STRING
    tenantId: "00000000-0000-0000-0000-000000000000"
