{{- if .Values.keyvault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-auth-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyvault.clientId | quote }}
    keyvaultName: {{ .Values.keyvault.name | quote }}
    objects: |
      array:
        {{- range .Values.keyvault.secrets }}
        - |
          objectName: {{ .name | quote }}
          objectType: secret
          objectAlias: {{ .alias | quote }}
        {{- end }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
{{- end }}
