apiVersion: apps/v1
kind: Deployment
metadata:
  name: archgen-prod-api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "acrarchgenprod.azurecr.io/api-gateway:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
