apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: archgen-prod-architecture-service-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "00000000-0000-0000-0000-000000000000"
    keyvaultName: "kv-archgen-prod"
    objects: |
      array:
        - |
          objectName: openai-api-key
          objectType: secret
          objectAlias: OPENAI_API_KEY
        - |
          objectName: deepseek-api-key
          objectType: secret
          objectAlias: DEEPSEEK_API_KEY
    tenantId: "00000000-0000-0000-0000-000000000000"
