apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: archgen-prod-auth-service-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "00000000-0000-0000-0000-000000000000"
    keyvaultName: "kv-archgen-prod"
    objects: |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
          objectAlias: JWT_SECRET
    tenantId: "00000000-0000-0000-0000-000000000000"
