apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-project-service
  labels:
    app: project-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: project-service
