apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-architecture-service
  labels:
    app: architecture-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: architecture-service
  template:
    metadata:
      labels:
        app: architecture-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Release.Name }}-architecture-service-sa
      containers:
        - name: architecture-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Release.Name }}-architecture-keyvault-provider"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
