replicaCount: 1

image:
  repository: acrarchgendev.azurecr.io/auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8001

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

keyvault:
  enabled: true
  name: "kv-archgen-dev"
  clientId: "00000000-0000-0000-0000-000000000000"
  tenantId: "00000000-0000-0000-0000-000000000000"
  secrets:
    - name: "jwt-secret"
      alias: "JWT_SECRET"

nodeSelector: {}
tolerations: []
affinity: {}
