apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-project-service-sa
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyvault.clientId | quote }}
  labels:
    app: project-service
